### ISSUE TITLE
Update to work with latest firebase / firestore updates

### ISSUE THREAD

**Issue by JayPerfetto** [Bestfastfire/multi_query_firestore#1]
This pack is not compatible with Firestore 0.14, or Firebase Core 0.5 - please update with the latest breaking changes from firebase

**Comment by Bestfastfire** [comment]
> This pack is not compatible with Firestore 0.14, or Firebase Core 0.5 - please update with the latest breaking changes from firebase

Will be updated soon.

**Comment by Bestfastfire** [comment]
Fixed!
